### ISSUE TITLE
Parking lot vehicle detection 

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#10]
As a system administrator, he would like to monitor the number of vehicles in the parking lot at any time

- [x] Come across a way to detect vehicle entry and exit the parking lot.
- [x] Provide deliverables for each alternative.
- [x] Identify risks for each alternative.

**Comment by ZhuoChenP** [comment]
The investigation has been done, decision has been made - using ai detection to count vehicles. Close the issue.
