### ISSUE TITLE
Content/Software management system Backend

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#12]
At the software level, the data should be handled and stored with security in mind

- [x] Provide API for sign in and sign out of the management system

**Comment by ziwentan** [comment]
Create an interface for login, which is implemented through spring security. The user information is verified first, and if the information entered is the same as that in the database, the authentication is passed. After that, the id of the authenticated account is encrypted into a Token and sent to the front-end. Meanwhile, the user information is stored in the cache with the user id as the key and the user information as the value. After that, each time the front-end sends an application, it carries the token. The back end will decrypt the token and check Redis for information with the id as the key. If so, this information is used as an index to query the information in the database.

**Comment by kevinren1108** [comment]
@ziwentan You can mention how you slove a task with a commit id, simply use a "#" sign in front of the commit id. I added it for you, you can try it out next time.
