### ISSUE TITLE
System Design

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#16]
Developers need to pick the right architecture to best suit the project.

- [x]  Clarify the scope of the system
- [x]  Identify constraints
- [x]  High-level architecture design
- [x]  Component Design
- [x]  Understanding Bottlenecks
- [x]  Scaling

**Comment by ziwentan** [comment]
The system design has been completed. Mainly for the A* algorithm, the optimization of the consumed resources of access. SQL input and read/write requires a lot of performance. Therefore, in the face of high concurrency, it is more likely to use caching. The advantage that Redis has is message queuing, which means that the requests made by the backend logic are only made in the order they were requested.Then there are Redis optimizations like sentinels, cache breakdown, etc.
