### ISSUE TITLE
Waypoint CRUD API

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#18]
- [x] Provide an API to upload a waypoint graph.
- [x] Provide an API to insert a new waypoint into the graph.
- [x] Provide an API to load the waypoint graph.
- [x] Provide an API to update a waypoint graph.
- [x] Provide an API to delete a waypoint graph.

| API endpoint | request                                                                                       | respond body                             | additional respond |
|--------------|-----------------------------------------------------------------------------------------------|------------------------------------------|--------------------|
| /uploadWP    | body: a waypoint graph object                                                                 | copy of request                          | 201,400            |
| /insertWP    | body: a object including new waypoint's ancestor and neighbor                                 | copy of request                          | 201,400            |
| /loadWP      | none                                                                                          | the graph if exist otherwise respond 500 |                    |
| /updateWP    | body: a object including a id of the waypoint to be update and new property for this waypoint | copy of request                          | 200,400            |
| /deleteWP    | body: a object including a id of the waypoint to be deleted                                   | copy of request                          | 200,400            |

**Comment by ziwentan** [comment]
all done
