### ISSUE TITLE
deploy a parking lot vehicle detection AI

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#25]
- [x] remove unnecessary function from yolo v5 or use yolo v3,v4. 
- [x] run a workable system to detect vehicles entering and exiting the parking lot on PC.

**Comment by ZhuoChenP** [comment]
Yolov5 could run on my PC with expected counting functions. All the configuration are done. Branch '25-deploy-a-parking-lot vehicle- detection-AI' has been created.

**Comment by kevinren1108** [comment]
> Yolov5 could run on my PC with expected counting functions. All the configuration are done. Branch '25-deploy-a-parking-lot vehicle- detection-AI' has been created.

Would be great to have a readme file that describes the deployment process. Maybe make a new folder called ezparking_ai to store it and any other related files.

**Comment by Kecheng-Yu** [comment]
The modification of YOLOv5 has been completed and has met our expectations. The detection lines can be adjusted and the vehicle type detection is limited to improve the operational efficiency
