### ISSUE TITLE
Prove the AI application on SBC

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#28]
- [x] Find a SBC(signal board computer) that can run this AI at a reasonable price.
- [x] Use the SBC to run the AI and prove it works.
- [x] Write a report to prove the vehicle detection AI application is keepable to run on the SBC

**Comment by ZhuoChenP** [comment]
Successfully deployed the AI vehicle solution to raspberry pi SBC.
