### ISSUE TITLE
Vehicle count APIs

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#29]
- [x] Provide an API to increase vehicle count for a specific parking lot
- [x] Provide an API to decrease vehicle count for a specific parking lot
- [x] Do some research on A* algorithm 

It is very important to make sure those APIs are lightweight 

| API endpoint       | request  | respond body      | additional respond |
|--------------------|----------|-------------------|--------------------|
| /incCount/plid?=id | none     | status code only  | 201,400            |
| /decCount/plid?=id | none     | status code only  | 201,400            |

**Comment by ziwentan** [comment]
all done
