### ISSUE TITLE
Lo-fidelity Design 

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#5]
Provide a lo-fidelity design for the project

- [x] Lo-fidelity design should include a visual design for the project
- [x] Lo-fidelity design should include a content design for the project
- [x] Lo-fidelity design should include an interactivity design for the project

**Comment by Kecheng-Yu** [comment]
Lofi design is completed with the file
[Lofi design](https://github.com/kevinren1108/Apollo-Capstone-Project/blob/74619d5efbdf8d364da73872d2042339af6f1ec8/design/lofi%20design.pdf)
