### ISSUE TITLE
User test Plan Week of Mar 6

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#52]
- [x] Add Client app user test plan
- [x] Add Myadmin app user test plan
- [x] Add AI detector app user test plan
- [x] [Example](https://github.com/ENSE-477-Fall2021-Winter2022/SolarSize/blob/main/Project%20Documentation/Testing/SolarSize%20-%20User%20Testing%20Plan%20and%20Results.pdf)

**Comment by Kecheng-Yu** [comment]
user testing report is done and merged to main
