### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by kevinren1108** [kevinren1108/Apollo-Capstone-Project#7]
Stakeholders need to have a visualized project roadmap

- [x] Analyse potential project tasks and propose them during the meeting.
- [x] Provide a Gantt Chart roadmap based on current tasks and milestones.

**Comment by ZhuoChenP** [comment]
Roadmap has been created, all the issues until Nov, 16 2022 have been imported to the Notion template. Close this issue, since it is in 1.5. Update roadmap issue will be reopen in the later stage.
